language: node_js

node_js: 10

sudo: required

# 使用安全列表指定要构建的分支
branches:
  only:
  - master
  - stable

# Travis-CI Caching
cache:
  directories:
    - node_modules


before_install:
  - sudo apt-get update
  - sudo apt-get install sshpass


script:
- npm i
- npm run build

addons:
  ssh_known_hosts:
   - $HOST

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" registry.cn-qingdao.aliyuncs.com
  - docker build  -t registry.cn-qingdao.aliyuncs.com/zealsay/zealsay_front:$TRAVIS_BRANCH .
  - docker push registry.cn-qingdao.aliyuncs.com/zealsay/zealsay_front:$TRAVIS_BRANCH;
  - sshpass -p $VPS_PASSWORD ssh -o stricthostkeychecking=no travis@$HOST "/home/zeal/docker/zealsay/deploy-beta.sh"


notifications:
  email:
    recipients:
      - zhangleifor@163.com
    on_success: change # default: change
    on_failure: always # default: always
